In [1]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [8]:
# Lista é uma estrutura de dados que armazena múltiplos valores em uma única variável, porém em análise de dados usamos muito mais arrays pois eles são mais performáticos e otimizadores para operações matemáticas e científicas.

import numpy as np

variavel = np.array([1,2,3,4,5])
print(variavel)

# A diferencial do array para a lista é que o array trabalha com dados homogênios, ou seja, do mesmo tipo!

var_mista = np.array([1, 'abc', 3, 4, 5])
print(type(var_mista))

for elemento in var_mista:
    print(type(elemento))

[1 2 3 4 5]
<class 'numpy.ndarray'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [9]:
print(variavel.shape)

(5,)


In [11]:
teste = np.arange(20)
teste

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [13]:
teste2 = np.arange(0, 100, 5)
teste2

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [18]:
matriz = np.linspace(0, 10, 5)
matriz

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
np.tile(np.array([ [0,1,2],[3,4,5] ]), [2,3])

array([[0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5]])

In [22]:
nova_lista = []

for i in variavel:
    nova_lista.append(i+1)

print(nova_lista)

[np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6)]


In [23]:
a = variavel+1
print(a)

[2 3 4 5 6]
